## 异常



### 什么是异常？

> 异常简单理解，就是非正常，没有达到预期目标。
> 异常是一个事件，并且这个异常事件在我们程序员的运行过程中出现，会影响我们程序正常执行。

异常分两种：
    1. 语法错误导致的异常
    2. 逻辑错误导致的异常

### 如何处理异常？

1. 如果错误发生的情况是可以预知的，那么就可以使用流程控制进行预防处理

```python
#比如： 两个数字的运算，其中一个不是数字，运算就会出错。这时可以去判断来预防
n2 = 3
if isinstance(n2,int):
    res = 10+n2
    print(res)
```

2. 如果错误的发生条件不可预知，就可以使用 try。。。except。。 在错误发生时进行处理

```python
'''语法：
try:
    可能发生异常错误的代码
except:
    如果发生异常则进入 except 代码块进行处理
'''

# 假设读取的文件不存在，会发生错误，可以使用两种方式进行处理，
# 1。可以在文件读取前先判断当前的文件是否存在
# 2。也可以使用try 。。。 except。。在错误发生时进行处理
try:
    with open('./user.txt','r') as fp:
        res = fp.read()
    print(res)
except:
    print('文件不存在')

print('程序的继续执行。。。')
```

**注意：try。。except。。是在错误发生后进行的处理。和if有着根本性的区别。**



### Try。。。except。。详细用法

```python
# try。。except 详细用法


# 1。使用try。。except 处理指定的异常。如果引发了非指定的异常，则无法处理
try:
    s1 = 'hello'
    int(s1) # 会引发 ValueError
except ValueError as e:
# except IndexError as e:  #如果引发了非指定的异常，则无法处理
    print(e)


# 2。 多分支处理异常类.不同的异常会走向不同的except处理
s1 = 'hello'
try:
    # int(s1) # ValueError
    s1[5]    # IndexError
except IndexError as e:
    print('IndexError',e)
except KeyError as e:
    print('KeyError',e)
except ValueError as e:
    print('ValueError',e)


# 3。通用异常类 Exception
s1 = 'world'
try:
    int(s1)
except Exception as e:
    print('Exception ===',e)


# 4. 多分支异常类+通用异常类.这样引发异常后会按照从上往下的顺序去执行对应的异常处理类。
s1 = 'hello'
try:
    # int(s1) # ValueError
    s1[5]    # IndexError
except IndexError as e:
    print('IndexError',e)
except KeyError as e:
    print('KeyError',e)
except ValueError as e:
    print('ValueError',e)
except Exception as e:
    print('Exception',e)


# 5。 try...except...else...
s1 = 'hello'
try:
    str(s1)
except IndexError as e:
    print('IndexError',e)
except ValueError as e:
    print('ValueError',e)
except Exception as e:
    print('Exception',e)
else:
    print('try代码块中没有引发异常时，执行')

# 6。try...except..else..finally
# finally 无论是否引发异常，都会执行。通常情况下用于执行一些清理工作。
s1 = 'hello'
try:
    int(s1)
    print('如果前面的代码引发了异常，这个代码块将不在继续执行。。')
except IndexError as e:
    print('IndexError',e)
except ValueError as e:
    print('ValueError',e)
except Exception as e:
    print('Exception',e)
else:
    print('try代码块中没有引发异常时，执行')
finally:
    print('无论是否引发了异常，都会执行这个代码块')

print('如果上面的代码有异常并且进行了处理，那么后面的代码将继续执行')


# 7。使用 raise ，主动抛出异常
try:
    #可以使用 raise 主动抛出异常，并设置异常信息
    raise Exception('发生错误')
except Exception as e:
    print('Exception',e)


#8。 assert 断言
assert 1 == 1 # 如果后面的表达式正确，则什么也不做
assert 2 == 1 # 如果后面的表达式错误，则直接抛出 AssertionError
```

### 自定义异常处理类

> 当异常出现时，对异常信息进行写入日志。

##### traceback 回溯模块  https://docs.python.org/3.7/library/traceback.html

##### logging 日志模块 https://docs.python.org/3.7/library/logging.html

```python
# 自定义异常日志处理类
class Myexception():
    def __init__(self):
        import traceback
        import logging

        # logging的基本配置
        logging.basicConfig(
            filename='./error.log',# 日志存储的文件及目录
            format='%(asctime)s  %(levelname)s \n %(message)s',# 格式化存储的日志格式
            datefmt='%Y-%m-%d %H:%M:%S'
        )
        # 写入日志
        logging.error(traceback.format_exc())

# 使用自定义异常处理类
try:
    int('bb')
except:
    print('在此处进行异常的处理')
    Myexception() # 在异常处理的代码块中去调用自定义异常类
```



### 标准的异常类

|         异常名称          |                        描述                        |
| :-----------------------: | :------------------------------------------------: |
|       BaseException       |                   所有异常的基类                   |
|        SystemExit         |                   解释器请求退出                   |
|     KeyboardInterrupt     |             用户中断执行(通常是输入^C)             |
|         Exception         |                   常规错误的基类                   |
|       StopIteration       |                 迭代器没有更多的值                 |
|       GeneratorExit       |        生成器(generator)发生异常来通知退出         |
|       StandardError       |              所有的内建标准异常的基类              |
|      ArithmeticError      |               所有数值计算错误的基类               |
|    FloatingPointError     |                    浮点计算错误                    |
|       OverflowError       |                数值运算超出最大限制                |
|     ZeroDivisionError     |            除(或取模)零 (所有数据类型)             |
|      AssertionError       |                    断言语句失败                    |
|      AttributeError       |                  对象没有这个属性                  |
|         EOFError          |             没有内建输入,到达EOF 标记              |
|     EnvironmentError      |                 操作系统错误的基类                 |
|          IOError          |                 输入/输出操作失败                  |
|          OSError          |                    操作系统错误                    |
|       WindowsError        |                    系统调用失败                    |
|        ImportError        |                 导入模块/对象失败                  |
|        LookupError        |                 无效数据查询的基类                 |
|        IndexError         |              序列中没有此索引(index)               |
|         KeyError          |                  映射中没有这个键                  |
|        MemoryError        |     内存溢出错误(对于Python 解释器不是致命的)      |
|         NameError         |            未声明/初始化对象 (没有属性)            |
|     UnboundLocalError     |               访问未初始化的本地变量               |
|      ReferenceError       | 弱引用(Weak reference)试图访问已经垃圾回收了的对象 |
|       RuntimeError        |                  一般的运行时错误                  |
|    NotImplementedError    |                   尚未实现的方法                   |
|        SyntaxError        |                  Python 语法错误                   |
|     IndentationError      |                      缩进错误                      |
|         TabError          |                   Tab 和空格混用                   |
|        SystemError        |                一般的解释器系统错误                |
|         TypeError         |                  对类型无效的操作                  |
|        ValueError         |                   传入无效的参数                   |
|       UnicodeError        |                 Unicode 相关的错误                 |
|    UnicodeDecodeError     |                Unicode 解码时的错误                |
|    UnicodeEncodeError     |                 Unicode 编码时错误                 |
|   UnicodeTranslateError   |                 Unicode 转换时错误                 |
|          Warning          |                     警告的基类                     |
|    DeprecationWarning     |               关于被弃用的特征的警告               |
|       FutureWarning       |           关于构造将来语义会有改变的警告           |
|      OverflowWarning      |        旧的关于自动提升为长整型(long)的警告        |
| PendingDeprecationWarning |              关于特性将会被废弃的警告              |
|      RuntimeWarning       |      可疑的运行时行为(runtime behavior)的警告      |
|       SyntaxWarning       |                  可疑的语法的警告                  |
|        UserWarning        |                 用户代码生成的警告                 |

 

